### ISSUE TITLE
GatewayWorker status command is not working

### ISSUE THREAD

**Issue by yayaigo2010** [walkor/GatewayWorker#10]
$ php start.php start -d
$ php start.php status   <<<< I can see the server status information                                                     

But second day, I can't see anything about status,why? 
[centos@ip-172-31-13-63 GatewayWorker]$ php start.php status                                                 
PHP Warning:  Module 'mcrypt' already loaded in Unknown on line 0
PHP Warning:  Module 'msgpack' already loaded in Unknown on line 0
Workerman[start.php] status

**Comment by walkor** [comment]
Try command ```strace php start.php status```.
You can see all system calls of the script. That may show why status not work.
