### ISSUE TITLE
不知道有没有打算支持composer？

### ISSUE THREAD

**Issue by hugtale** [walkor/GatewayWorker#11]
个人愚见，把GatewayWorker核心和workerman的核心用composer来加载。这个项目就当是一个官方实例。^_^

**Comment by walkor** [comment]
谢谢你的建议。
我也想这么干，但是国内很多phper不熟悉composer，对他们来说使用门槛稍高。
workerman目前是支持composer的。

**Comment by lingfengchencn** [comment]
composer 越用越多，同样建议支持 composer

**Comment by tank-chan** [comment]
@walkor 建议把gatewayworker直接独立出来吧。连composer都不会用的phper，你更不用指望他们能用好GatewayWorker或者Workerman。

**Comment by liyu001989** [comment]
@walkor 是不是可以像这样 https://github.com/liyu001989/GatewayWorker

base 分支是没有 composer 的版本
master 是 @hugtale 的做法

**Comment by walkor** [comment]
好的，我考虑下将这个项目作为GatewayWorker的核心添加到composer.

**Comment by walkor** [comment]
各位，已经支持composer了。感谢大家的支持，有问题可以继续提问。

**Comment by liyu001989** [comment]
👍 💯
