### ISSUE TITLE
sentToUid和sendToClient推送失败

### ISSUE THREAD

**Issue by skyfister** [walkor/GatewayWorker#14]
冒昧的请教下：在使用GatewayWorker的时候(websocket)，在events.php文件onMessage函数里面使用sendToAll能推送给客户端成功接收，但是使用sendToUid和sendToClient给指定客户端推送消息，可能是什么原因呢？

**Comment by walkor** [comment]
debug方式运行(php start.php start)，看看有没有什么报错。
一般是参数传错了

**Comment by skyfister** [comment]
没有报错哈，debug模式下运行过

**Comment by walkor** [comment]
可能是参数传错了，打下日志看看吧。client_id是否对。
也可以抓包看看，或者下载workerman-chat，这个聊天室有sendToClient私聊的功能，看是否正常。
没有报错，没有日志我这确实很难定位

**Comment by skyfister** [comment]
日志没有报错哈，Gateway::sendToClient($client_id, json_encode(["type" => "message", 'content' => $msg->content])); Gateway::sendToAll(json_encode(["type" => "message", "clientId" => $client_id, 'content' => $msg->content])); 第一个收不到，第二个能收到，那我先试试workerman-chat

**Comment by skyfister** [comment]
$client_id直接用的客户端上报的那个参数，public static function onMessage($client_id, $message) {

**Comment by skyfister** [comment]
已解决，registerAddress端口没有统一设置成1236，自己给自己挖了个坑，谢了
