### ISSUE TITLE
GatewayClient::closeClient

### ISSUE THREAD

**Issue by sm2017** [walkor/GatewayWorker#15]
GatewayClient::closeClient is not working in Distributed Deployment
I cannot close a client connect to server #2 from server #1

Also Please implement closeUid
https://github.com/walkor/GatewayClient/issues/2
Best regards

**Comment by walkor** [comment]
Is there any error message for GatewayClient::closeClient ?

Can you show your codes of start_gateway.php?

**Comment by sm2017** [comment]
> Is there any error message for GatewayClient::closeClient ?
No

>Can you show your codes of start_gateway.php?
I test https://github.com/walkor/workerman-chat also without any changes


Please run 2 server , and connect a client to server #1 , and try to GatewayClient::closeClient that is placed in server #2 , it dont works

**Comment by walkor** [comment]
https://github.com/walkor/workerman-chat/blob/master/Applications/Chat/Web/index.php#L32
Workerman-chat client will reconnect after disconnection, so GatewayClient::closeClient seems not work on workerman-chat.
