### ISSUE TITLE
GatewayClient

### ISSUE THREAD

**Issue by sm2017** [walkor/GatewayWorker#18]
Which is newer?
https://github.com/walkor/GatewayClient/blob/master/Gateway.php
OR
https://github.com/walkor/GatewayWorker/blob/master/src/Lib/Gateway.php

And I think it is better to add ```GatewayClient``` as a dependency of ```GatewayWorker``` using composer

**Comment by walkor** [comment]
They are not exactly the same library.
GatewayClient/blob/master/Gateway.php is SDK for any project run on apache or php-fpm to control GatewayWorker(send message, get session, set session, join group etc).
GatewayWorker/blob/master/src/Lib/Gateway.php is API witch must run on GatewayWorker.

All of them will be  keep the synchronization update.

**Comment by sm2017** [comment]
In https://github.com/walkor/GatewayClient we have 
```php
Gateway::$registerAddress = 'x.x.x.x:xx';
```

Is it required to set ```registerAddress``` for ```GatewayWorker/blob/master/src/Lib/Gateway.php```?
Now I don't set it but it works for me in  Distributed Deployment , I use ```GatewayWorker/blob/master/src/Lib/Gateway.php``` form business workers to send message to clients

**Comment by walkor** [comment]
> Is it required to set registerAddress for GatewayWorker/blob/master/src/Lib/Gateway.php?

Gateway::$registerAddress will be automatically obtained from  $businessworker->registerAddress witch defined in start_businessworker.php.
