### ISSUE TITLE
Integration with swoole

### ISSUE THREAD

**Issue by sm2017** [walkor/GatewayWorker#24]
Hello

Swoole is an Event-driven asynchronous & concurrent & coroutine networking engine with high performance for PHP. 

Here is Github repository https://github.com/swoole/swoole-src

There is some advantage over workerman , So I want to replace GatewayWorker with swoole but I want to connect swoole to register and business worker , How is possible?

I want to keep all GatewayWorker features like Distributed deployment

Best Regards

**Comment by walkor** [comment]
You can try to implement GatewayWorker with swoole.
