### ISSUE TITLE
Send command to business worker

### ISSUE THREAD

**Issue by sm2017** [walkor/GatewayWorker#28]
Hi

According to the following codes
https://github.com/walkor/GatewayWorker/blob/master/src/Gateway.php#L409-L414

each client is indirectly connected to specific business worker

From another business worker I want to send a command to the specific business worker using `clientId`

In other words , If I have business worker A (BWA) and B (BWB) and `clientId` = X is connected to BWA , Some times I need from BWB send a command to BWA that do something

How is possible ?

**Comment by sm2017** [comment]
@wenzhihong2003 
any update ?

**Comment by walkor** [comment]
There is a interprocess/multi-server communication component for workerman named [channel](https://github.com/walkor/Channel).

Install workerman\channel with command
```conposer require workerman/channel```

Example.
Create Applications/YourProject/start_channel.php.
```php
<?php
use Workerman\Worker;
require_once __DIR__ . '/vendor/autoload.php';

// Channel Server. 
$channel_server = new Channel\Server('0.0.0.0', 2206);
```

In Events.php.
```php
Class Events
{
    public static function onWorkerStart($worker)
    {
        // Channel client connect to Channel Server.
        Channel\Client::connect('127.0.0.1', 2206);
        // Subscribe $worker->id event . 
        Channel\Client::on($worker->id, function($event_data){
             var_export($event_data);
        });
    }

    public static function onMessage($client_id, $data) {
        // Publish event to one business worker processes which id is 1.
        $worker_id = 1;
        $event_data = ['some', 'data...'];
        Channel\Client::publish($worker_id, $event_data);
    }
}
```

Refer https://github.com/walkor/Workerman/issues/175.

Sorry for the delay.
