### ISSUE TITLE
react async mysql in gateway

### ISSUE THREAD

**Issue by jbkingsley** [walkor/GatewayWorker#29]
Hi, worker,
according to the example in workman, I used it in gateway, but it doesn't work, the client could not receive the message!
```php
$asyncMysql->query('select * from user', function ($command, $mysql) {
            if ($command->hasError()) {
                $error = $command->getError();
            } else {
                $results = $command->resultRows;
                $fields  = $command->resultFields;
                \GatewayWorker\Lib\Gateway::sendToCurrentClient(json_encode($results));
            }
        });
```
I also use sendToUid replace to sendToCurrentClient ..... same problem
Do I need use $connections as workerman example? If so, how can i get $connect in gateway

**Comment by walkor** [comment]
```php
        $asyncMysql->query('select * from user', function ($command, $mysql) {
            if ($command->hasError()) {
                $error = $command->getError();
                var_dump($error);
            } else {
                $results = $command->resultRows;
                $fields  = $command->resultFields;
                var_dump($results);
                \GatewayWorker\Lib\Gateway::sendToCurrentClient(json_encode($results));
            }
        });
```

Please try these codes and run gatewayWorker as debug mode ```php start.php start``` (no ```-d```) see if there is any output in your terminal.

**Comment by jbkingsley** [comment]
I have tried it.  $results can be printed on screen, but message can not be sent out.
Now I try the below code,  It is worked. 

$connection = Gateway();
$client_id = Context.client_id;
$asyncMysql->query('select * from user', function ($command, $mysql) use($connection, $client_id ) {
            if ($command->hasError()) {
                $error = $command->getError();
            } else {
                $results = $command->resultRows;
                $fields  = $command->resultFields;
                $connection::sendToClient(client_id , json_encode($results));
            }
        });

**Comment by walkor** [comment]
I found the problem, ```Gateway::sendToCurrentClient``` can not found who is the current client because ```Gateway::sendToCurrentClient``` in an asynchronous callback without context of the client. So use ```Gateway::sendToClient``` will work.

**Comment by jbkingsley** [comment]
Hi walkor,
If we directly use method " Gateway::sendToClient " in callback, it will not be worked.
We should new Gateway() then use in function
