### ISSUE TITLE
GatewayWorker的配置使用REDIS时，createGlobalClientId超出最大值时报错

### ISSUE THREAD

**Issue by templar87** [walkor/GatewayWorker#3]
超出最大值后，REDIS中GLOBAL_CLIENT_ID_KEY 的值为“i:0;"
log记录为
createGlobalClientId fail  GatewayWorker\Lib\StoreDriver\Redis  ERR not an integar or out of range.

 redis版本号为
Redis server v=3.0.3 sha=00000000:0 malloc=jemalloc-3.6.0 bits=64 build=e2c78c7971ad5d9e

**Comment by walkor** [comment]
目前版本GatewayWorker已经不依赖redis扩展了。
