### ISSUE TITLE
The log records some errors. How to handle them?

### ISSUE THREAD

**Issue by sbqqqf5** [walkor/GatewayWorker#31]
[ 2017-08-24T14:07:50+08:00 ][ error ] [2]file_get_contents(/var/www/game/vendor/workerman/workerman/../_var_www_game_worker_start.php.pid): failed to open stream: No such file or directory
[ 2017-08-24T14:07:57+08:00 ][ error ] [2]stream_select(): unable to select [4]: Interrupted system call (max_fd=9)
[ 2017-08-24T14:07:57+08:00 ][ error ] [2]stream_select(): unable to select [4]: Interrupted system call (max_fd=9)
[ 2017-08-24T14:07:57+08:00 ][ error ] [2]stream_select(): unable to select [4]: Interrupted system call (max_fd=11)
[ 2017-08-24T14:12:21+08:00 ][ error ] [2]stream_select(): unable to select [4]: Interrupted system call (max_fd=12)
[ 2017-08-24T14:12:21+08:00 ][ error ] [2]stream_select(): unable to select [4]: Interrupted system call (max_fd=9)
[ 2017-08-24T14:12:21+08:00 ][ error ] [2]stream_select(): unable to select [4]: Interrupted system call (max_fd=9)
[ 2017-08-24T14:22:38+08:00 ][ error ] [2]stream_select(): unable to select [4]: Interrupted system call (max_fd=12)
[ 2017-08-24T14:22:38+08:00 ][ error ] [2]stream_select(): unable to select [4]: Interrupted system call (max_fd=9)
[ 2017-08-24T14:22:38+08:00 ][ error ] [2]stream_select(): unable to select [4]: Interrupted system call (max_fd=9)

**Comment by walkor** [comment]
Please update workerman and install event extension for php.
