### ISSUE TITLE
按手册进行telnet操作时出现致命bug

### ISSUE THREAD

**Issue by walkermanuser** [walkor/GatewayWorker#32]
PHP Fatal error:  Class '' not found in D:\wwwroot\GatewayWorker-for-win\vendor\
workerman\workerman-for-win\Connection\TcpConnection.php on line 310

**Comment by walkor** [comment]
贴下你的代码

**Comment by walkermanuser** [comment]
刚按照手册从"http://www.workerman.net/download/GatewayWorker-for-win.zip"下载的代码,唯一修改的地方是将start_for_win.bat里的
php Applications\YourApp\start_register.php Applications\YourApp\start_gateway.php Applications\YourApp\start_businessworker.php
pause
改为
php -c D:\php_5.6.2\php.ini  Applications\YourApp\start_register.php Applications\YourApp\start_gateway.php Applications\YourApp\start_businessworker.php start
pause

**Comment by walkermanuser** [comment]
walkor你好
我刚按照手册从"http://www.workerman.net/download/GatewayWorker-for-win.zip"下载的代码,唯一修改的地方是将start_for_win.bat里的
php Applications\YourApp\start_register.php Applications\YourApp\start_gateway.php Applications\YourApp\start_businessworker.php
pause
改为
php -c D:\php_5.6.2\php.ini Applications\YourApp\start_register.php Applications\YourApp\start_gateway.php Applications\YourApp\start_businessworker.php start
pause

**Comment by walkor** [comment]
不要做修改试下
