### ISSUE TITLE
65280错误代码日志

### ISSUE THREAD

**Issue by hufeng903** [walkor/GatewayWorker#33]
1.用status命令查看，有很多65280的错误。这种错误日志在什么地方？ 还是需要自己代码里面做处理？
2.默认的项目里面也没有生成workerman.log日志，是需要设置什么？
麻烦帮忙答疑，谢谢！

**Comment by walkor** [comment]
65280 是致命错误，如果你在php.ini 里设置了php的错误日志路径，可以在php的日志里找到。
workerman.log里也会记录致命错误的日志，在workerman平行的目录里。

**Comment by hufeng903** [comment]
@walkor 谢谢
