### ISSUE TITLE
Limits

### ISSUE THREAD

**Issue by sm2017** [walkor/GatewayWorker#35]
@walkor if we have many powerful machines
How many gateway and business worker can exist in workerman  system ??

If we choose `libevent` or `event` as main event loop

**Comment by sm2017** [comment]
No I ask about connection limits . As you know each gateway is connected to business workers and vise versa . So if we increase gateways each business worker must handle more connections

My question is about distributed system

**Comment by walkor** [comment]
In theory, the number of gateway processes can't exceed 1000, and business can't exceed 60000 In the whole distributed system.
In fact, I think the best number of gateway processes is less than 200, and business is around 200-600 In the whole distributed system.
Because I don't have so many servers, the above data is my guess value.

**Comment by sm2017** [comment]
Can you explain why??
>In theory, the number of gateway processes can't exceed 1000, and business can't exceed 60000

How you calculate 1000? And 60000?
If we use `select` we have a 1024 limitation but for `event` and `libevent` the limit is 100k (if I'm wrong correct me)

Please explain in details .Please check your Bitter , I want to chat you

**Comment by walkor** [comment]
[src/Lib/Gateway.php](https://github.com/walkor/GatewayWorker/blob/master/src/Lib/Gateway.php ) called ```stream_select``` in ```getBufferFromAllGateway``` method which limit gateway process count can not exceed 1000. Of course, this can be changed to use event to process.

About business count , 60000 is not inaccurate. It is limited by ```open files``` of linux kernel configuration maybe 65535 or other values.

**Comment by sm2017** [comment]
To handling 100 million concurrent connection , is there any recommendation?

**Comment by sm2017** [comment]
@walkor please reply

**Comment by walkor** [comment]
Don't put all 100 million connections in the same cluster.
You can scatter connections in multiple clusters.
There is no business communication between clusters is better.
