### ISSUE TITLE
how to onmessage for laravel framework

### ISSUE THREAD

**Issue by GodRuffian** [walkor/GatewayWorker#38]
@walkor 我想应用您写的GatewayWorker，我在laravel console 分别创建了StartRegister.php、StartBusinessworker.php、StartGateway.php 我在浏览器console请求websocket是成功的，请问在laravel 框架里我改怎么接受 websocket 数据呢？

**Comment by walkor** [comment]
抱歉，github只接受英文的issue. 中文社区在这里 http://wenda.workerman.net/。

**Comment by walkor** [comment]
没用过laravel。
可以参考gateway手册与其它框架结合部分。
