### ISSUE TITLE
Gateway: Worker->name conflict.

### ISSUE THREAD

**Issue by sm2017** [walkor/GatewayWorker#39]
I have too many `Gateway: Worker->name conflict.` error in log

Why?

**Comment by sm2017** [comment]
@walkor help me please

**Comment by sm2017** [comment]
@walkor I am still waiting for your response

**Comment by sm2017** [comment]
@walkor 😭

**Comment by walkor** [comment]
Do not start the same business worker again in the same machine.

**Comment by sm2017** [comment]
@walkor I don't do it , just after days of starting , I see too many this error

**Comment by walkor** [comment]
You can use command ```ps aux``` to see if any machine start business workers with the same name.

**Comment by walkor** [comment]
Closing this due to a lack of feedback.
