### ISSUE TITLE
建议增加一个CMD_GET_SESSION命令获取某客户端的session

### ISSUE THREAD

**Issue by hehbhehb** [walkor/GatewayWorker#4]
与CMD_UPDATE_SESSION相配套， 建议增加一个CMD_GET_SESSION命令获取任一用户（而不是当前用户）的session, 

或者说是提供一个getClientInfo()函数

**Comment by sukui** [comment]
是可以实现，只是比较好奇干嘛需要这个？

**Comment by sxmwhl** [comment]
增加这个可以跨用户获取在线信息

**Comment by sukui** [comment]
用户信息直接从数据库读取不就好了？

**Comment by sxmwhl** [comment]
在数据库读影响性能，session保持在内存里了，直接读快！

**Comment by sukui** [comment]
这个跟业务场景相关很大。  例如说一个用户他没登录的话你还不是一样要去数据库获取他的信息.
如果要性能使用nosql缓存用户的信息，这样处理比较好点.

**Comment by hehbhehb** [comment]
场景理解错了

**Comment by sukui** [comment]
新版本已经增加支持了

**Comment by hehbhehb** [comment]
谢谢
