### ISSUE TITLE
packet size limit

### ISSUE THREAD

**Issue by yayaigo2010** [walkor/GatewayWorker#40]
I found  if the data size is large, `sendToGroup()` will split the string then send next time. 
How to know and set packet size limit?

**Comment by walkor** [comment]
Which protocol do you use for gateway?

**Comment by yayaigo2010** [comment]
tcp

**Comment by walkor** [comment]
Your application should an application layer protocol. 
See https://stackoverflow.com/questions/756765/when-will-a-tcp-network-packet-be-fragmented-at-the-application-layer
