### ISSUE TITLE
worker[ChatGateway:76703] exit with status 11

### ISSUE THREAD

**Issue by cenchy** [walkor/GatewayWorker#41]
**命令**
git clone https://github.com/walkor/workerman-chat
cd workerman-chat/
composer install
php start.php start

** 版本**
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing workerman/workerman (v3.5.6)
    Loading from cache
  - Installing workerman/gateway-worker (v3.0.7)
    Loading from cache

**出现下面的情况**

Workerman[start.php] start in DEBUG mode
----------------------- WORKERMAN -----------------------------
Workerman version:3.5.6          PHP version:7.0.27
------------------------ WORKERS -------------------------------
user          worker              listen                    processes status
xxxxx     ChatBusinessWorker  none                       4         [OK]
xxxxx     ChatGateway         websocket://0.0.0.0:7272   4         [OK]
xxxxx     Register            text://0.0.0.0:1236        1         [OK]
xxxxx     WebServer           http://0.0.0.0:55151       2         [OK]
----------------------------------------------------------------
Press Ctrl+C to stop. Start success.
worker[ChatGateway:76065] exit with status 11
worker[ChatGateway:76064] exit with status 11
worker[ChatGateway:76063] exit with status 11
worker[ChatBusinessWorker:76062] exit with status 11
worker[ChatGateway:76066] exit with status 11
worker[ChatBusinessWorker:76061] exit with status 11
worker[ChatBusinessWorker:76060] exit with status 11
worker[ChatBusinessWorker:76059] exit with status 11
worker[ChatGateway:76072] exit with status 11
worker[ChatGateway:76071] exit with status 11
worker[ChatGateway:76073] exit with status 11
worker[ChatGateway:76075] exit with status 11
worker[ChatBusinessWorker:76074] exit with status 11
worker[ChatBusinessWorker:76076] exit with status 11
worker[ChatBusinessWorker:76078] exit with status 11
worker[ChatGateway:76079] exit with status 11
worker[ChatGateway:76080] exit with status 11
worker[ChatGateway:76082] exit with status 11
worker[ChatGateway:76081] exit with status 11
worker[ChatBusinessWorker:76083] exit with status 11
worker[ChatGateway:76086] exit with status 11
worker[ChatGateway:76087] exit with status 11
worker[ChatBusinessWorker:76085] exit with status 11
worker[ChatGateway:76088] exit with status 11
worker[ChatGateway:76089] exit with status 11
worker[ChatBusinessWorker:76084] exit with status 11
worker[ChatGateway:76092] exit with status 11
worker[ChatGateway:76091] exit with status 11
worker[ChatGateway:76094] exit with status 11
worker[ChatGateway:76095] exit with status 11
....

**Comment by walkor** [comment]
看下是不是装了swoole
