### ISSUE TITLE
Gateway stream_select

### ISSUE THREAD

**Issue by sm2017** [walkor/GatewayWorker#42]
In the following line
https://github.com/walkor/GatewayWorker/blob/master/src/Lib/Gateway.php#L774

you use `stream_select` , it is better to use event loops
Can I ask what is `$client_array` ? is it all connected users for example all web socket connections? or it is just  Gateway->BusinessWorker connections?

**Comment by walkor** [comment]
Yes, event loops is better.
$client_array is just Gateway->BusinessWorker connections.

**Comment by sm2017** [comment]
@walkor can you please implement it by event loops?
Because currently we are limited to 1024 gateways and we cannot have more gateway

**Comment by walkor** [comment]
I don't have time to do it, you can do it by yourself.
