### ISSUE TITLE
getAllClientSessions & getSession 获取到的session信息不一致

### ISSUE THREAD

**Issue by insomniazz** [walkor/GatewayWorker#44]
getAllClientSessions 获取到的对应的client有session,而使用getSession获取次client的session为空

![image](https://user-images.githubusercontent.com/26534573/41405421-514756d8-6ffc-11e8-8a62-6d68b4345123.png)
![image](https://user-images.githubusercontent.com/26534573/41405494-70e7ca4a-6ffc-11e8-8d3a-49aeaa19a3e9.png) 

Workerman_version : 3.5.10
Gatewayworker_version : 3.0.9

**Comment by walkor** [comment]
我这里没有重现出这个问题，看看能否写一个可以重现问题的简单的demo，整体打包发到邮箱 walkor@workerman.net 。邮件里写明重现的步骤。

**Comment by walkor** [comment]
Closing this due to a lack of feedback.
