### ISSUE TITLE
How to transmit video or pictures while chatting

### ISSUE THREAD

**Issue by niyaode** [walkor/GatewayWorker#48]
How to transmit video or pictures while chatting，The way through the flow
聊天时如何传输视频或图片，以流的方式

**Comment by walkor** [comment]
服务端直接传递即可，gatewayWorker不关心传递的是什么数据

**Comment by niyaode** [comment]
我说的是，客户端发一张图片或一段视频怎么用webSocket发送出去，发送出去的是什么格式的数据，是IO（流）吗？服务端如何接收发给他人，而接收的图片或视频资源不在服务器存留
I mean, how does a client send a picture or a piece of video sent out with webSocket, what format of data is sent out, IO?How does the server receive a picture or a video resource that is not on the server

**Comment by walkor** [comment]
```javascript
var inputElement = document.getElementById("file");
var file = inputElement.files;
var reader = new FileReader();
//以二进制形式读取文件
reader.readAsArrayBuffer(file);
//文件读取完毕后该函数响应
reader.onload = function loaded(evt) {
        var binaryString = evt.target.result;
                //发送文件
        ws.send(binaryString);
}
```
以上是从网上搜的浏览器读取本地文件发送给服务端的代码。
服务端接收是在Events.php里
```php
public static onMessage($client_id, $data) {
    // $data  里是图片或者视频数据，这里又发给了$other_client_id
    Gateway::sendToClient($other_client_id, $data);
}
```
有一点要注意的是浏览器要求服务端发送二进制数据时要在数据包包头加入一个标记
start_gateway.php 里适当位置加入下面的代码设置这个标记
```php
$gateway->onConnect = function($connection){
    $connection->websocketType = Websocket::BINARY_TYPE_ARRAYBUFFER;
};
```

所以不管客户端是什么，传递的是什么数据，GatewayWorker里$data就是客户端发送的数据。要给某个客户端发送数据也是将数据放在$data变量里send即可。

最后不建议用websocket转发视频或者图片数据，因为图片或者视频数据很大，如果消息和文件传输是同一个连接会造成消息延迟。比如A客户给B发送了一个视频文件，然后马上给C发送了一条消息，那么根据TCP机制，必须全部文件数据发到服务器(文件大比较耗时)后服务器才会收到给C的消息然后才能将消息转发给C，造成聊天延迟。通用做法是http上传图片或者视频文件，得到一个url地址，然后利用websocket将地址发送给其它客户端，客户端收到地址后用img 或者 video 标签通过http协议下载，这样开发最简单，也不会造成消息延迟。

**Comment by walkor** [comment]
方案要自己想了
