### ISSUE TITLE
can't trigger Timer function

### ISSUE THREAD

**Issue by yayaigo2010** [walkor/GatewayWorker#5]
$task = new Worker();
$task->name = 'YourAppTestTimer';
$task->count = 1;
$task->onWorkerStart = function($task)
{
    $time_interval = 2.5;
    Timer::add($time_interval, "timerProcess",array(),true);
};

function timerProcess(){
    $t = ORM::for_table("test")->find_one(1);
    $t->end_time = Carbon::now()->toDateTimeString();
    $t->save();
        
    echo "task run\n";
}
Worker::runAll();

use "php start.php start" it will execute timerProcess every 2.5 seconds.
But use "php start.php start -d" , it won't exceute timerProcess function.why?

**Comment by walkor** [comment]
```php start.php start``` is debug mode and output buffer will be printed to terminal.
```php start.php start -d``` is daemon mode and output buffer will be redirect to /dev/null by default.
You can change the redirect path by setting ```Worker::$stdoutFile = '/tmp/stdout.log';``` and then you can see the output buffer by ```tail -f /tmp/stdou.log```.

**Comment by yayaigo2010** [comment]
Ok ,I found the error about "mysql gone away", I must use GatewayWorker build-in DB function. 
refer to :http://www.workerman.net/gatewaydoc-1.0/appendices/mysql.html
