### ISSUE TITLE
Gateway不能和Register采用相同的配置格式

### ISSUE THREAD

**Issue by ctfang** [walkor/GatewayWorker#50]
例如 

`
$coket = ‘text://0.0.0.0:3238’;
new Register($coket);

$gateway = new Gateway("ws://0.0.0.0:8070");
$gateway->registerAddress = $socket;
`
报错信息

`Warning: stream_socket_client(): php_network_getaddresses: getaddrinfo failed: Name or service not known in`

**Comment by walkor** [comment]
根据手册，registerAddress 必须是ip:port格式，其中ip不能是0.0.0.0，不能复用new Register($address)里的$address格式
