### ISSUE TITLE
GatewayWorker 不能优雅退出

### ISSUE THREAD

**Issue by yuchonghua** [walkor/GatewayWorker#51]
GatewayWorker 优雅退出是会被卡在的，而workerman却是可以的

**Comment by walkor** [comment]
GatewayWorker不支持优雅退出

**Comment by yuchonghua** [comment]
判断逻辑可能有问题，方便有话逻辑？

**Comment by yuchonghua** [comment]
那如果同时有http和ws应该在调用优雅退出的时候强退ws部分，不应该卡死

**Comment by yuchonghua** [comment]
或者说能否实现，BusinessWorker优雅退出，Gateway不退出，Register不退出，但是命令行不要卡在

**Comment by walkor** [comment]
GatewayWorker里reload本来就是Gateway和Register不退出，BusinessWorker优雅退出，所以直接reload即可

**Comment by yuchonghua** [comment]
明白，可是我同时还开了http服务，这个呢

**Comment by walkor** [comment]
你可以单独开个http服务

**Comment by yuchonghua** [comment]
谢谢，我们交个朋友
