### ISSUE TITLE
React/stomp  (要求Workerman版本>=3.3.6) 

### ISSUE THREAD

**Issue by Sparkxxx** [walkor/GatewayWorker#52]
Hello Walkor, 

Very nice work you did with the Worker project.
While looking at documentation for GatewayWorker I found out on React/stomp page that
Note: This item has expired and cannot be used. Do not install

Is this true? Is there a versioning mismatch ?
Can it now be used?

Thank you.

**Comment by walkor** [comment]
Unfortunately it can not be used.

**Comment by Sparkxxx** [comment]
Thank you,
I will go for mqtt client which is what I wanted anyway.
