### ISSUE TITLE
Set headers from Events.php

### ISSUE THREAD

**Issue by Sparkxxx** [walkor/GatewayWorker#53]
Hi Walkor

I am trying to set some custom headers when replying to client from inside Events.php run from businessWorker and can't figure out how to do it.

http server is started in the gateway.php with:
	// gateway FwUpdHttpGateway process
		$FwUpdHttpGateway = new Gateway("http://0.0.0.0:9090");

	

In Events.php
	public static function onMessage($client_id, $message){
		# Use Workerman\Protocols\Http::header to send header to clients.
		# https://github.com/walkor/Workerman/issues/151
					Http::header("Content-type: text/plain");
					Http::header("Accept-Ranges: bytes");
					Http::header("Content-Disposition: attachment; filename=test");

     		$fw_update_data = array(
			"version" => $fwupd_name,
			"firmware" => "?".$fwupd_name
		); 
    		$fw_update_data = json_encode($fw_update_data);

    		#Send data to client
         	 Gateway::sendToClient($_SERVER['GATEWAY_CLIENT_ID'], $fw_update_data);
	}

Thankx

**Comment by Sparkxxx** [comment]
I've possibly found out the reason that the code is not working as expected.

In Workerman\Protocols\Http.php line 92 there is the declaration of the array that will store the heades
HttpCache::$header   = array('Connection' => 'Connection: keep-alive');

What is happening is that when I set new custom headers with 
      Http::header("Content-Disposition: attachment; filename=test");
and var_dump(HttpCache::$header); at line 311 inside function header (line 280 ) I get all the correct headers 
      /vendor/workerman/workerman/Protocols/Http.php:311:
      array(3) {
      'Server' => string(13) "Server: test"
      'Connection' =>  string(17) "Connection: close"
      'x-Cucu' =>  string(12) "x-Cucu: mucu"
      }
But these headers are not sent to the client (checked with Wireshark) and I think that HttpCache::$header is reseted to default before being used in function encode (line 235) or something loopy is happening.

Hope this helps.

**Comment by walkor** [comment]
GatewayWorker is suitable for full duplex communication applications. HTTP is a request/response protocol and is not suitable for GatewayWorker. GatewayWorker did not consider supporting HTTP protocol when it was designed. HTTP protocol is more suitable for workerman.

**Comment by Sparkxxx** [comment]
Thank you Walkor, you are right, I solved the problem using a stand alone WebServer where adding headers works like a charm.

Still learning....
