### ISSUE TITLE
gatewaywork集群下有多台gateway服务器，客户端（PC、APP）应该连接哪一个gateway？

### ISSUE THREAD

**Issue by keehao** [walkor/GatewayWorker#56]
gatewaywork集群下有多台gateway服务器，客户端（PC、APP）应该连接哪一个gateway？
比如：
1，192.168.1.1机器的start_gateway.php配置$gateway = new Gateway("Websocket://192.168.1.1:7272");
2，192.168.1.2机器的start_gateway.php配置$gateway = new Gateway("Websocket://192.168.1.2:7272");
这时候客户端应该如何做，还是随机的连接这两个gateway任意一个？

**Comment by walkor** [comment]
客户端随意连一个即可。
可以在客户端前加一个负载均衡，例如
1、可以用域名添加2个A记录，dns会自动选择一个ip供客户端连
2、可以加一个lvs(类似阿里云的slb)，lvs会自动转发消息给后端一个ip
3、可以加一个haproxy/nginx类似的代理，代理会自动转发消息给后端一个ip
