### ISSUE TITLE
php7.3.2下，使用thinkphp5.1的数据库连接，导致worker进程退出

### ISSUE THREAD

**Issue by zhiyuanfirst** [walkor/GatewayWorker#58]
测试机：mac10.14.1
php环境：7.3.2
框架版本：thinkphp5.1
gatewayworker版本："workerman/gateway-worker": "^3.0"
错误：使用th5的orm或连接导致worker进程退出；worker[MedicalBoxWorker:920] exit with status 11
补充：
（1）此错误Exception无法捕获；
（2）在php7.1环境没有问题;
（3）Worker::runAll()启动前可用使用DB，Events中的回调（onWorkerStart，onConnect，onMessage）无法使用

**Comment by walkor** [comment]
status 11是发生了coredump，php的7.3.2版本还不够稳定，尽量不要小版本太低的php。
