### ISSUE TITLE
不同协议间心跳设置

### ISSUE THREAD

**Issue by sxmwhl** [walkor/GatewayWorker#6]
不同协议间心跳设置是相通的，能否加以区分？

**Comment by walkor** [comment]
每种协议可以单独设置心跳参数，比如心跳间隔、心跳数据等

**Comment by sxmwhl** [comment]
我用了JsonNL和WS两种协议，设置其中一个心跳监测，另外一个不设置，两个客户端都能收到{‘type':'ping'}

**Comment by walkor** [comment]
不会有这个问题，你可以贴下两个gateway的代码

**Comment by sxmwhl** [comment]
两个文件设置如下，还请指教，谢谢！

start_gateway.php
========================================
<?php 
use \Workerman\Worker;
use \Workerman\WebServer;
use \GatewayWorker\Gateway;
use \GatewayWorker\BusinessWorker;
use \Workerman\Autoloader;

// 自动加载类
require_once __DIR__ . '/../../Workerman/Autoloader.php';
Autoloader::setRootPath(__DIR__);

// gateway 进程，这里使用Text协议，可以用telnet测试
$gateway = new Gateway("JsonNL://0.0.0.0:8181");
// gateway名称，status方便查看
$gateway->name = 'Json_name';
// gateway进程数
$gateway->count = 2;
// 本机ip，分布式部署时使用内网ip
$gateway->lanIp = '127.0.0.1';
// 内部通讯起始端口，假如$gateway->count=4，起始端口为4000
// 则一般会使用4000 4001 4002 4003 4个端口作为内部通讯端口 
$gateway->startPort = 9000;
// 服务注册地址
$gateway->registerAddress = '127.0.0.1:1239';

// 心跳间隔
//$gateway->pingInterval = 10;
// 心跳数据
//$gateway->pingData = '{"type":"ping"}';
/* 
// 当客户端连接上来时，设置连接的onWebSocketConnect，即在websocket握手时的回调
$gateway->onConnect = function($connection)
{
    $connection->onWebSocketConnect = function($connection , $http_header)
    {
        // 可以在这里判断连接来源是否合法，不合法就关掉连接
        // $_SERVER['HTTP_ORIGIN']标识来自哪个站点的页面发起的websocket链接
        if($_SERVER['HTTP_ORIGIN'] != 'http://kedou.workerman.net')
        {
            $connection->close();
        }
        // onWebSocketConnect 里面$_GET $_SERVER是可用的
        // var_dump($_GET, $_SERVER);
    };
}; 
*/

// 如果不是在根目录启动，则运行runAll方法
if(!defined('GLOBAL_START'))
{
    Worker::runAll();
}
=================================================================
start_ws_gateway.php
=================================================================
<?php 
use \Workerman\Worker;
use \Workerman\WebServer;
use \GatewayWorker\Gateway;
use \GatewayWorker\BusinessWorker;
use \Workerman\Autoloader;
// 自动加载类
require_once __DIR__ . '/../../Workerman/Autoloader.php';
Autoloader::setRootPath(__DIR__);

// ##########新增端口支持Text协议 开始##########
// 新增8383端口，开启Text文本协议
$gateway_text = new Gateway("Websocket://0.0.0.0:8383");
// 进程名称，主要是status时方便识别
$gateway_text->name = 'BigiotWSGateway';
// 开启多少http协议的gateway进程
$gateway_text->count = 2;
// 本机ip（分布式部署时需要设置成内网ip）
$gateway_text->lanIp = '127.0.0.1';
// 设置服务注册地址
$gateway_text->registerAddress = '127.0.0.1:1239';
// gateway内部通讯起始端口，起始端口不要重复
$gateway_text->startPort = 2500;
// 也可以设置心跳，这里省略
$gateway->pingInterval = 30;
$gateway->pingNotResponseLimit = 2;
$gateway->pingData = '{"type":"ping"}';

/*
 // 当客户端连接上来时，设置连接的onWebSocketConnect，即在websocket握手时的回调
 $gateway->onConnect = function($connection)
 {
 $connection->onWebSocketConnect = function($connection , $http_header)
 {
 // 可以在这里判断连接来源是否合法，不合法就关掉连接
 // $_SERVER['HTTP_ORIGIN']标识来自哪个站点的页面发起的websocket链接
 if($_SERVER['HTTP_ORIGIN'] != 'http://chat.workerman.net')
 {
 $connection->close();
 }
 // onWebSocketConnect 里面$_GET $_SERVER是可用的
 // var_dump($_GET, $_SERVER);
 };
 };
 */

if(!defined('GLOBAL_START'))
{
    Worker::runAll();
}

**Comment by sxmwhl** [comment]
找到错误之处了：
$gateway_text->startPort = 2500;
// 也可以设置心跳，这里省略
$gateway->pingInterval = 30;
两个文件的设置的new Gateway() 变量串了。
$gateway $gateway_text
粗心了，谢谢！
