### ISSUE TITLE
uid长时间在线后， uid对应的gateway clientid 会生成好几个并同时在线的问题

### ISSUE THREAD

**Issue by lurrui** [walkor/GatewayWorker#60]
**问题描述：**
              uid长时间在线后（几个小时，或者更长不一定）， uid对应的gateway clientid 会生成好几个并同时在线(websocket连接)，导致该账号无法收到消息。

**架构方面。**
 webclient->云服务负载均衡转发->服务器 gateway，Business一体 无分离

**问题排查：**  

1. 怀疑 客户端 重连机制引起，导致new了多个实例。（检查代码后没有问题）
2. 怀疑  开启了多个 接入网页，导致clientid 增多  （已严格控制，并确保只有一个账号登陆）
3. 怀疑  一些程序、电脑未知问题导致 。 （在发现有多个clientid同时在线后，直接关闭网页 或者禁用网卡，来触发服务端关闭连接，发现只有一个被关闭了。剩下clientid的还在）
4. 怀疑 服务端问题， 直接在服务端中 重启gateway所有相关服务 ，该uid对应的clientid全部消失，发现那些多出来的clientid 并没有因为重连机制 再次连接上来。  

至此 锁定了大致的范围 在 服务端。  但无法进一步排查，所以请您帮忙分析一下，以进一步锁定范围。
(虽然可以将消息，转发给uid对应的所有clientid ，但是不到万不得已不能使用这个偏方)

**Comment by walkor** [comment]
bindUid的时候把uid client_id $_SERVER['REMOTE_ADDR'] 记录在日志里，onClose的时候记录下client_id， 然后根据日志看下uid绑定的client_id是哪些ip发过来的。

**Comment by lurrui** [comment]
> bindUid的时候把uid client_id $_SERVER['REMOTE_ADDR'] 记录在日志里，onClose的时候记录下client_id， 然后根据日志看下uid绑定的client_id是哪些ip发过来的。

这个也试过了， php start.php start 的时候不后台运行， 直接 程序内对 这个账号的进行dump() 打印监控， 查看 他的连接断线过程。 的确是同一个ip  ，因为 目前应用场景是 这个账号属于客服类，长期在线。

**Comment by lurrui** [comment]
我测试环境直连没什么问题。可能跟我的架构有关系。  负载均衡器->云服务器docker->nginx反向ws代理 ->gateway  我再查一下吧。 谢谢啦。

**Comment by walkor** [comment]
根据手册 http://doc2.workerman.net/heartbeat.html
设置下gateway心跳，设置
```php
$gateway->pingInterval = 55;
$gateway->pingNotResponseLimit = 1;
```
其中 pingNotResponseLimit 必须要设置。
这样如果客户端55秒不发任何数据过来，服务端就断开连接，这样可以用来清理一些僵尸连接。
你的这个问题也有可能是一些僵尸连接导致的，就是实际上连接已经断开了，但是操作系统检测不到，需要用心跳来检测。
