### ISSUE TITLE
PHPDoc incorrect type client ID 

### ISSUE THREAD

**Issue by tezrik** [walkor/GatewayWorker#61]
Incorrect type in php doc

https://github.com/walkor/GatewayWorker/blob/38b44c95f21cd340b5a9cff3987ddb2abb9a2a38/src/Lib/Gateway.php#L802
https://github.com/walkor/GatewayWorker/blob/38b44c95f21cd340b5a9cff3987ddb2abb9a2a38/src/Lib/Gateway.php#L812
https://github.com/walkor/GatewayWorker/blob/38b44c95f21cd340b5a9cff3987ddb2abb9a2a38/src/Lib/Context.php#L124

**Comment by walkor** [comment]
Thanks.
