### ISSUE TITLE
Error: Call to undefined method Workerman\Protocols\Http::getMimeTypesFile()

### ISSUE THREAD

**Issue by bin20060407** [walkor/GatewayWorker#67]
https://github.com/walkor/workerman-chat/ 项目
`gateway-worker` composer 配置 : 
```
"require": {
        "workerman/workerman" : ">=3.1.8"
 }
```
执行 `composer install`，就会安装，`workerman/workerman (v4.0.0)` 然后就会报上面这个错误
问题的重点在于本项目的版本配置依赖，应该是依赖于 3.* 版本，不超过 4.0

```
"require": {
        "workerman/workerman" : "^3.1.8"
 }
```

**Comment by bin20060407** [comment]
workerman 发布了 4.0，理论上相关 package 因为依赖配置错误原因，都会有这个问题

**Comment by walkor** [comment]
已经修改了依赖
