### ISSUE TITLE
Gateway通讯地址为空，省略if这部分验证

### ISSUE THREAD

**Issue by twomiao** [walkor/GatewayWorker#68]
public function checkGatewayConnections($addresses_list)
    {
        if (empty($addresses_list)) {
            return;
        }
        foreach ($addresses_list as $addr) {
            if (!isset($this->_waitingConnectGatewayAddresses[$addr])) {
                $this->tryToConnectGateway($addr);
            }
        }
    }
  修改为：
public function checkGatewayConnections($addresses_list)
    {
        // $addresses_list 本身为数组，既然为空就可以省略这部分验证呢。
        foreach ($addresses_list as $addr) {
            if (!isset($this->_waitingConnectGatewayAddresses[$addr])) {
                $this->tryToConnectGateway($addr);
            }
        }
    }

**Comment by walkor** [comment]
加不加判断都可以，判断下这个方法会更健壮些。
