### ISSUE TITLE
Socket Connection refused

### ISSUE THREAD

**Issue by yayaigo2010** [walkor/GatewayWorker#7]
I create inbound rule Custom TCP rule port 10001 in aws

I create socket server connection by Php GatewayWorker, the port is 10001.

telnet public ip result is No route to host, how to fix it?

[centos@ip-private ip ~]$ telnet [private ip] 10001
Trying [private ip]...
Connected to [private ip].
Escape character is '^]'.

[centos@ip-private ip ~]$ telnet [public ip] 10001
Trying [public ip]...
telnet: connect to address [public ip]: No route to host

[centos@ip-private ip ~]$ telnet [public ip] 80                                                                                                                              
Trying [public ip] ...
Connected to [public ip] .
Escape character is '^]'.

**Comment by yayaigo2010** [comment]
systemctl stop iptables.service

**Comment by walkor** [comment]
:+1:
