### ISSUE TITLE
Gateway.php 326行代码问题

### ISSUE THREAD

**Issue by twomiao** [walkor/GatewayWorker#80]
Gateway进程代码：
` if ($connection->protocol === '\Workerman\Protocols\Websocket' || $connection->protocol === 'Workerman\Protocols\Websocket') {`

问题：
这两个条件写一个就好了，完全重复了呢。

**Comment by twomiao** [comment]
> Gateway进程代码： ` if ($connection->protocol === '\Workerman\Protocols\Websocket' || $connection->protocol === 'Workerman\Protocols\Websocket') {`
> 
> 问题： 这两个条件写一个就好了，完全重复了呢。

**Comment by twomiao** [comment]
> Gateway进程代码： ` if ($connection->protocol === '\Workerman\Protocols\Websocket' || $connection->protocol === 'Workerman\Protocols\Websocket') {`
> 
> 问题： 这两个条件写一个就好了，完全重复了呢。

发现不同之处了。

**Comment by xpader** [comment]
感觉 `ltrim($connection->protocol, '\\') === 'Workerman\Protocols\Websocket'` 是不是更好一点？
