### ISSUE TITLE
How to avoid single point of failure

### ISSUE THREAD

**Issue by nskushwah** [walkor/GatewayWorker#84]
Hi Walkor,

I want to avoid single point of failure so need to understand: 

Suppose if the Registers goes down then what will happen to the existing connection and new connection? Also if we restart the Register then all the previous connections will be lost?

What will happen if one Business worker crashes? How are Gateway workers forwarded to another Business worker?

Regards,
Narottam

**Comment by walkor** [comment]
Hi nskushwah
Here are the answers https://github.com/walkor/GatewayWorker/issues/83#issuecomment-990667859 .

**Comment by nskushwah** [comment]
Thanks
