### ISSUE TITLE
Log file doesn't often show new log 

### ISSUE THREAD

**Issue by yayaigo2010** [walkor/GatewayWorker#9]
I open three GatewayWorker Servers  in an operating system.
I have the same code in three different folder ,and the folder structure is below:

Peter or Leon or Test folder
-GatewayWorker
--Applications
--- YourApp
---- Config 
----- Config.php (add by myslef)
------ Db.php
------ Store.php
...(Skip)

this is Test's Config.php code blow:
$port = 8282;
$logFileNamePostfix = "";

this is Peter's Config.php code blow:
$port = 8283;
$logFileNamePostfix = "Peter";
 
this is Leon's Config.php code blow:
$port = 8284;
$logFileNamePostfix = "Leon";

the $port will apply for "$gateway = new Gateway("Text://0.0.0.0:".$port);"
the $logFileNamePostfix will apply for  
"Worker::$stdoutFile = '/var/log/TTT_SocketServer_'.$logFileNamePostfix.Carbon::now()->toDateString().'.log';" in start_bussinessworker.php

So I execute "php start.php start -d" in three different folder, I get three server using different port.
and output server log into three different file.

I found that three Log file doesn't often show new log,sometimes it show log,but sometimes it dosen't.
why?

**Comment by walkor** [comment]
It's strange.
May be that time did not produce any log.
