### ISSUE TITLE
你好，请问聊天IM这类项目，使用Gatewayworker 会数据丢失？

### ISSUE THREAD

**Issue by twomiao** [walkor/GatewayWorker#97]
gateway 基于workerman, workerman 每个连接都分配了10MB左右的接收内存，如果客户端发送过快，这时候接收内存满了。
那这后来的消息就全丢失了，请问有什么好一点的技术方案解决？
所以就看见有人说gateway worker 不适合有一定规模的IM，这一般用哪些技术来做比较合适呢？【PHP 来做的话】

**Comment by walkor** [comment]
https://www.workerman.net/q/9114
